plugins:
  - jekyll-katex
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown

kramdown:
  math_engine: katex

theme: jekyll-theme-primer

github:
  private: true
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/hyhieu/hyhieu.github.io"

title: ''
