plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# markdown: kramdown

# kramdown:
#   math_engine: null

exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: true
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/hyhieu/hyhieu.github.io"

title: ''
